RestClients:
  tel-search:
    UUID: 20621516-9434-437b-8a8d-d41da2e7917b
    Url: https://tel.search.ch/api/
    Icon: res:/webContent/icons/searchCH200x200.png
    Features:
    - com.axonivy.telsearch.AtomXmlFeature
    - com.axonivy.telsearch.AuthKeyFeature
